{-# OPTIONS --cubical --safe #-}
module Cubical.HITs.Everything where

import Cubical.HITs.2GroupoidTruncation
import Cubical.HITs.AssocList
import Cubical.HITs.Colimit
import Cubical.HITs.Cylinder
import Cubical.HITs.DunceCap
import Cubical.HITs.FiniteMultiset
import Cubical.HITs.GroupoidTruncation
import Cubical.HITs.Hopf
import Cubical.HITs.InfNat
import Cubical.HITs.Interval
import Cubical.HITs.Ints.BiInvInt
import Cubical.HITs.Ints.DeltaInt
import Cubical.HITs.Ints.HAEquivInt
import Cubical.HITs.Ints.IsoInt
import Cubical.HITs.Ints.QuoInt
import Cubical.HITs.Ints.QuoInt.Properties
import Cubical.HITs.Join
import Cubical.HITs.KleinBottle
import Cubical.HITs.ListedFiniteSet
import Cubical.HITs.Localization
import Cubical.HITs.MappingCones
import Cubical.HITs.Modulo
import Cubical.HITs.Nullification
import Cubical.HITs.PropositionalTruncation
import Cubical.HITs.Pushout
import Cubical.HITs.Pushout.Flattening
import Cubical.HITs.RPn
import Cubical.HITs.Rational
import Cubical.HITs.S1
import Cubical.HITs.S2
import Cubical.HITs.S3
import Cubical.HITs.SetQuotients
import Cubical.HITs.SetTruncation
import Cubical.HITs.SmashProduct
import Cubical.HITs.Sn
import Cubical.HITs.Susp
import Cubical.HITs.Torus
import Cubical.HITs.Truncation
