{-# OPTIONS --safe #-}
module Cubical.HITs.Everything where

import Cubical.HITs.2GroupoidTruncation
import Cubical.HITs.AbPath
import Cubical.HITs.AssocList
import Cubical.HITs.Bouquet
import Cubical.HITs.Bouquet.Discrete
import Cubical.HITs.Colimit
import Cubical.HITs.Cost
import Cubical.HITs.CumulativeHierarchy
import Cubical.HITs.Cylinder
import Cubical.HITs.Delooping.Two.Base
import Cubical.HITs.Delooping.Two.Properties
import Cubical.HITs.DunceCap
import Cubical.HITs.EilenbergMacLane1
import Cubical.HITs.FiniteMultiset
import Cubical.HITs.FiniteMultiset.CountExtensionality
import Cubical.HITs.FreeAbGroup
import Cubical.HITs.FreeComMonoids
import Cubical.HITs.FreeGroup
import Cubical.HITs.FreeGroup.NormalForm
import Cubical.HITs.FreeGroupoid
import Cubical.HITs.GroupoidQuotients
import Cubical.HITs.GroupoidTruncation
import Cubical.HITs.InfNat
import Cubical.HITs.Interval
import Cubical.HITs.James
import Cubical.HITs.James.Inductive
import Cubical.HITs.James.Inductive.Coherence
import Cubical.HITs.James.LoopSuspEquiv
import Cubical.HITs.James.Stable
import Cubical.HITs.Join
import Cubical.HITs.KleinBottle
import Cubical.HITs.ListedFiniteSet
import Cubical.HITs.Localization
import Cubical.HITs.MappingCones
import Cubical.HITs.Modulo
import Cubical.HITs.Nullification
import Cubical.HITs.PropositionalTruncation
import Cubical.HITs.PropositionalTruncation.Monad
import Cubical.HITs.Pushout
import Cubical.HITs.Pushout.Flattening
import Cubical.HITs.Pushout.PushoutProduct
import Cubical.HITs.RPn
import Cubical.HITs.Replacement
import Cubical.HITs.S1
import Cubical.HITs.S2
import Cubical.HITs.S3
import Cubical.HITs.SequentialColimit
import Cubical.HITs.SetCoequalizer
import Cubical.HITs.SetQuotients
import Cubical.HITs.SetQuotients.EqClass
import Cubical.HITs.SetTruncation
import Cubical.HITs.SetTruncation.Fibers
import Cubical.HITs.SmashProduct
import Cubical.HITs.SmashProduct.Hexagon
import Cubical.HITs.SmashProduct.Pentagon
import Cubical.HITs.SmashProduct.SymmetricMonoidal
import Cubical.HITs.SmashProduct.SymmetricMonoidalCat
import Cubical.HITs.Sn
import Cubical.HITs.Sn.Degree
import Cubical.HITs.Sn.Multiplication
import Cubical.HITs.SphereBouquet
import Cubical.HITs.SphereBouquet.Degree
import Cubical.HITs.Susp
import Cubical.HITs.Susp.LoopAdjunction
import Cubical.HITs.Susp.SuspProduct
import Cubical.HITs.Torus
import Cubical.HITs.Truncation
import Cubical.HITs.TypeQuotients
import Cubical.HITs.UnorderedPair
import Cubical.HITs.Wedge
