name: Nix
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - '**.nix'
      - 'flake.lock'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
      - name: Build
        run:  nix build -v --print-build-logs
